name: Terraform AWS Deployment with OIDC

on:
  push:
    branches:
      - main
      - infrastructure

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Configure AWS credentials
        id: aws-oidc
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::586794448788:role/github_full_2
          role-session-name: GitHubActionsSession
          aws-region: us-west-2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
